### ISSUE TITLE
Alert title cause editing failing if include a "/"

### ISSUE THREAD

**Issue by TiNico22** [airbus-cyber/graylog-plugin-alert-wizard#4]
If the title include a "/" the modify option is not working anymore because the page is not found
For example if the rule name is mytitle/foo
A parsing issue add extra /Foo  to the 
/wizard/UpdateAlert/mytitle/foo/foo which is not the right URL

Do not use / in title name until bugfix

**Comment by dlancelin** [comment]
The issue has been fixed with the version [1.1.1](https://github.com/airbus-cyber/graylog-plugin-alert-wizard/releases/tag/1.1.1).

**Comment by frantz45** [comment]
This issue is still present in the version 3.0.1 (with Graylog 3.0.2).
